#ifndef STYLE_H
#define STYLE_H

#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_RESET   "\x1b[0m"

#define LCLR ANSI_COLOR_RESET

#define LINIT	"["ANSI_COLOR_CYAN"INIT"ANSI_COLOR_RESET"]\t\t"
#define LOK		"["ANSI_COLOR_GREEN"OK"ANSI_COLOR_RESET"]\t\t"
#define LWARN	"["ANSI_COLOR_YELLOW"WARN"ANSI_COLOR_RESET"]\t\t"
#define LERR	"["ANSI_COLOR_RED"ERR"ANSI_COLOR_RESET"]\t\t"
#define LEND	"["ANSI_COLOR_MAGENTA"END"ANSI_COLOR_RESET"]\t\t"
#define LINFO	"["ANSI_COLOR_BLUE"INFO"ANSI_COLOR_RESET"]\t\t"
#define LDBG	"["ANSI_COLOR_CYAN"DBG"ANSI_COLOR_RESET"]\t\t"

#endif
